server:
  port: 8080
  servlet:
    session:
      timeout: 7200s
  tomcat:
    basedir: logistics/tomcat

image:
  size: 500

spring:
  datasource:
    url: jdbc:mysql://192.168.197.24:3306/coffee?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 10000
      initial-size: 5
      min-idle: 5
      max-active: 10
      validation-query: SELECT 1
      test-on-borrow: true
      test-while-idle: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.MySQL5Dialect
        cache:
          use_query_cache: false
          use_second_level_cache: false
  jta:
    log-dir: logs/admin-transaction

  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: false
    request-context-attribute: request
    settings:
      number_format: 0.#

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    com.tk.outer.coffee: debug
